- name: download_package
  get_url:
   url: https://s3-ap-southeast-2.amazonaws.com/<>/{{ packagename }}
   dest: /tmp/{{ packagename }}

- name: install_package
  command: dpkg -i /tmp/{{ packagename }}

- name: restart_app
  service: name=app state=restarted
